version: '3.1'
services:
  app:
    build: .
    command: python api.py
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0?encoding=utf-8
  redis:
    image: redis
    ports:
      - "6380:6379"

